server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-repair-list
          uri: lb://ms-repair-list:8091
          predicates:
            - Path=/api/v1/repair-list/**
        - id: ms-repairs
          uri: lb://ms-repairs:8092
          predicates:
            - Path=/api/v1/reparation/**
        - id: ms-reports
          uri: lb://ms-reports:8093
          predicates:
            - Path=/api/v1/report/**
        - id: ms-vehicles
          uri: lb://ms-vehicles:8094
          predicates:
            - Path=/api/v1/cars/**