server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-repair-list
          uri: lb://ms-repair-list:8091
          predicates:
            - Path=/api/v1/repair-list/**
        - id: ms-repairs
          uri: lb://ms-repairs:8092
          predicates:
            - Path=/api/v1/reparation/**
        - id: ms-reports
          uri: lb://ms-reports:8093
          predicates:
            - Path=/api/v1/report/**
        - id: ms-vehicles
          uri: lb://ms-vehicles:8094
          predicates:
            - Path=/api/v1/cars/**