server:
  port: 8093
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/reports-db
    username: postgres
    password: postgres
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka