apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-repairs-deployment
  labels:
    app: ms-repairs-deployment
spec:
  selector:
    matchLabels:
      app: ms-repairs-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-repairs-deployment
    spec:
      containers:
        - name: ms-repairs
          image: skyrdow/t2-ms-repairs
          ports:
            - containerPort: 8092
          env:
            - name: SERVER_PORT
              value: "8092"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_ORDERS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_ORDERS
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_ORDERS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_ORDERS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_ORDERS
---
apiVersion: v1
kind: Service
metadata:
  name: ms-repairs-service
  labels:
    app: ms-repairs-service
spec:
  selector:
    app: ms-repairs-deployment
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
  type: LoadBalancer